// APPLICATIONS

export const OPEN_TERMINAL = "OPEN_TERMINAL"
export const CLOSE_TERMINAL = "CLOSE_TERMINAL"
export const MINIMIZE_TERMINAL = "MINIMIZE_TERMINAL"

export const OPEN_MINESWEEPER = "OPEN_MINESWEEPER"
export const CLOSE_MINESWEEPER = "CLOSE_MINESWEEPER"
export const MINIMIZE_MINESWEEPER = "MINIMIZE_MINESWEEPER"


export const OPEN_PORTFOLIO = "OPEN_PORTFOLIO"
export const CLOSE_PORTFOLIO = "CLOSE_PORTFOLIO"
export const MINIMIZE_PORTFOLIO = "CLOSE_PORTFOLIO"


export const OPEN_PROGRAM = "OPEN_PROGRAM"
export const CLOSE_PROGRAM = "CLOSE_PROGRAM"
export const MINIMIZE_PROGRAM = "MINIMIZE_PROGRAM"

export const OPEN_PROFILE = "OPEN_PROFILE"
export const CLOSE_PROFILE = "CLOSE_PROFILE"
export const MINIMIZE_PROFILE = "MINIMIZE_PROFILE"


export const OPEN_NAVIGATION_MENU = "OPEN_NAVIGATION_MENU"
export const CLOSE_NAVIGATION_MENU = "CLOSE_NAVIGATION_MENU"

export const OPEN_SETTINGS = "OPEN_SETTINGS"
export const CLOSE_SETTINGS = "CLOSE_SETTINGS"
export const MINIMIZE_SETTINGS = "MINIMIZE_SETTINGS"

export const OPEN_DOCUMENTS = "OPEN_DOCUMENTS"
export const CLOSE_DOCUMENTS = "CLOSE_DOCUMENTS"
export const MINIMIZE_DOCUMENTS = "MINIMIZE_DOCUMENTS"

export const OPEN_HELP = "OPEN_HELP"
export const CLOSE_HELP = "CLOSE_HELP"
export const MINIMIZE_HELP = "MINIMIZE_HELP"


// COMPUTER

export const OPEN_COMPUTER = "OPEN_COMPUTER";
export const CLOSE_COMPUTER = "CLOSE_COMPUTER";


// FILES

export const OPEN_RESUME = "OPEN_RESUME";
export const CLOSE_RESUME = "CLOSE_RESUME";
export const MINIMIZE_RESUME = "MINIMIZE_RESUME";

//GITHUB

export const GET_REPOS = "GET_REPOS";
export const GET_REPOS_ERR = "GET_REPOS_ERR";
export const SET_CURR_REPO = "SET_CURR_REPO";
export const SET_PATH = "SET_PATH";
export const GO_BACK = "GO_BACK";
export const GO_FORWARD = "GO_FORWARD";
export const GITHUB_HOME = "GITHUB_HOME"


export const GET_CODE = "GET_CODE";

export const GET_CONTENT = "GET_CONTENT";
export const GET_CONTENT_ERR ="GET_CONTENT_ERR";